package app.aaps.core.keys

enum class DoubleKey(
    override val key: String,
    override val defaultValue: Double,
    override val min: Double,
    override val max: Double,
    override val defaultedBySM: Boolean = false,
    override val calculatedBySM: Boolean = false,
    override val showInApsMode: Boolean = true,
    override val showInNsClientMode: Boolean = true,
    override val showInPumpControlMode: Boolean = true,
    override val dependency: BooleanPreferenceKey? = null,
    override val negativeDependency: BooleanPreferenceKey? = null,
    override val hideParentScreenIfHidden: Boolean = false
) : DoublePreferenceKey {

    OverviewInsulinButtonIncrement1("key_insulin_button_increment_1", 0.5, -5.0, 5.0, defaultedBySM = true, dependency = BooleanKey.OverviewShowInsulinButton),
    OverviewInsulinButtonIncrement2("key_insulin_button_increment_2", 1.0, -5.0, 5.0, defaultedBySM = true, dependency = BooleanKey.OverviewShowInsulinButton),
    OverviewInsulinButtonIncrement3("key_insulin_button_increment_3", 2.0, -5.0, 5.0, defaultedBySM = true, dependency = BooleanKey.OverviewShowInsulinButton),
    ActionsFillButton1("key_fill_button_1", 0.3, 0.05, 20.0, defaultedBySM = true, hideParentScreenIfHidden = true),
    ActionsFillButton2("key_fill_button_2", 0.0, 0.05, 20.0, defaultedBySM = true),
    ActionsFillButton3("key_fill_button_3", 0.0, 0.05, 20.0, defaultedBySM = true),
    SafetyMaxBolus("key_safety_max_bolus", 3.0, 0.1, 60.0),
    ApsMaxBasal("key_openaps_max_basal", 1.0, 0.1, 25.0, defaultedBySM = true, calculatedBySM = true),
    ApsSmbMaxIob("Key_openaps_smb_max_iob", 3.0, 0.0, 70.0, defaultedBySM = true, calculatedBySM = true),
    ApsAmaMaxIob("key_openaps_ama_max_iob", 1.5, 0.0, 25.0, defaultedBySM = true, calculatedBySM = true),
    ApsMaxDailyMultiplier("key_openaps_max_daily_safety_multiplier", 3.0, 1.0, 10.0, defaultedBySM = true),
    ApsMaxCurrentBasalMultiplier("key_openaps_current_basal_safety_multiplier", 4.0, 1.0, 10.0, defaultedBySM = true),
    ApsAmaBolusSnoozeDivisor("Key_openaps_ama_bolus_snooze_dia_divisor", 2.0, 1.0, 10.0, defaultedBySM = true),
    ApsAmaMin5MinCarbsImpact("key_openaps_ama_min_5m_carbs_impact", 3.0, 1.0, 12.0, defaultedBySM = true),
    ApsSmbMin5MinCarbsImpact("key_openaps_smb_min_5m_carbs_impact", 8.0, 1.0, 12.0, defaultedBySM = true),
    AbsorptionCutOff("key_absorption_cutoff", 6.0, 4.0, 10.0),
    AbsorptionMaxTime("key_absorption_maxtime", 6.0, 4.0, 10.0),
    AutosensMin("key_openaps_autosens_min", 0.7, 0.1, 1.0, defaultedBySM = true, hideParentScreenIfHidden = true),
    AutosensMax("key_openaps_autosens_max", 1.2, 0.5, 3.0, defaultedBySM = true),
    ApsAutoIsfMin("key_openapsama_autoISF_min", 1.0, 0.3, 1.0, defaultedBySM = true),
    ApsAutoIsfMax("key_openapsama_autoISF_max", 1.0, 1.0, 3.0, defaultedBySM = true),
    ApsAutoIsfBgAccelWeight("key_openapsama_bgAccel_ISF_weight", 0.0, 0.0, 1.0, defaultedBySM = true),
    ApsAutoIsfBgBrakeWeight("key_openapsama_bgBrake_ISF_weight", 0.0, 0.0, 1.0, defaultedBySM = true),
    ApsAutoIsfLowBgWeight("key_openapsama_lower_ISFrange_weight", 0.0, 0.0, 2.0, defaultedBySM = true),
    ApsAutoIsfHighBgWeight("key_openapsama_higher_ISFrange_weight", 0.0, 0.0, 2.0, defaultedBySM = true),
    ApsAutoIsfPpWeight("key_openapsama_pp_ISF_weight", 0.0, 0.0, 1.0, defaultedBySM = true),
    ApsAutoIsfDuraWeight("key_openapsama_dura_ISF_weight", 0.0, 0.0, 3.0, defaultedBySM = true),
    ApsAutoIsfSmbDeliveryRatio("key_openapsama_smb_delivery_ratio", 0.5, 0.1, 1.0, defaultedBySM = true),
    ApsAutoIsfSmbDeliveryRatioMin(".key_openapsama_smb_delivery_ratio_min", 0.5, 0.1, 1.0, defaultedBySM = true),
    ApsAutoIsfSmbDeliveryRatioMax("key_openapsama_smb_delivery_ratio_max", 0.5, 0.5, 1.0, defaultedBySM = true),
    ApsAutoIsfSmbMaxRangeExtension("key_openapsama_smb_max_range_extension", 1.0, 1.0, 5.0, defaultedBySM = true),
    EquilMaxBolus("key_equil_maxbolus", 10.0, 0.1, 25.0),
    FslCalOffset("key_fslCal_Offset", 0.0, -50.0, 50.0, defaultedBySM = true),    // TODO: resolve UnitDouble problem
    FslCalSlope("key_fslCal_Slope", 1.0, 0.5, 1.5, defaultedBySM = true),
    FslSmoothAlpha("key_fsl_exp1_factor", 1.0, 0.01, 1.0, defaultedBySM = true),
    FslSmoothCorrection("key_fsl_exp1_correction", 0.0, 0.0, 1.0, defaultedBySM = true),
    FslLastRaw("key_fsl_last_raw", -1.0, 40.0, 400.0, defaultedBySM = true),
    FslLastSmooth("key_fsl_last_smooth", -1.0, 40.0, 400.0, defaultedBySM = true),

}